import type { DrugData } from "@/types";

// This file is now deprecated as we use real data from Supabase
export const mockDrugData: DrugData[] = [
  {
    id: 1,
    drugName: "Paracetamol 500mg",
    activeIngredient: "Paracetamol",
    concentration: "500mg",
    gdklh: "VN-12345-23",
    routeOfAdministration: "Uống",
    dosageForm: "Viên nén",
    expiryDate: "12/2025",
    manufacturer: "Công ty Dược Hậu Giang",
    manufacturingCountry: "Việt Nam",
    packaging: "Hộp 10 vỉ x 10 viên",
    unit: "Viên",
    quantity: 1000,
    unitPrice: 500,
    drugGroup: "Giảm đau, hạ sốt",
    tbmt: "Gói thầu số 1",
    investor: "Bệnh viện A",
    contractorSelectionMethod: "Đấu thầu rộng rãi",
    kqlcntUploadDate: "01/03/2024",
    decisionNumber: "123/QĐ-BV",
    decisionDate: "28/02/2024",
    contractorNumber: "NT001",
    location: "Khoa Dược, Bệnh viện A",
  },
  {
    id: 2,
    drugName: "Amoxicillin 250mg",
    activeIngredient: "Amoxicillin",
    concentration: "250mg/5ml",
    gdklh: "VD-67890-22",
    routeOfAdministration: "Uống",
    dosageForm: "Bột pha hỗn dịch",
    expiryDate: "06/2026",
    manufacturer: "Công ty CP Traphaco",
    manufacturingCountry: "Việt Nam",
    packaging: "Chai 60ml",
    unit: "Chai",
    quantity: 500,
    unitPrice: 15000,
    drugGroup: "Kháng sinh",
    tbmt: "Gói thầu mua sắm thuốc",
    investor: "Sở Y Tế tỉnh B",
    contractorSelectionMethod: "Chào hàng cạnh tranh",
    kqlcntUploadDate: "15/02/2024",
    decisionNumber: "45/QĐ-SYT",
    decisionDate: "10/02/2024",
    contractorNumber: "NT002",
    location: "Trung tâm Y tế huyện C",
  },
  {
    id: 3,
    drugName: "Omeprazole 20mg",
    activeIngredient: "Omeprazole",
    concentration: "20mg",
    gdklh: "US-11223-21",
    routeOfAdministration: "Uống",
    dosageForm: "Viên nang cứng",
    expiryDate: "09/2025",
    manufacturer: "Pfizer Inc.",
    manufacturingCountry: "Mỹ",
    packaging: "Lọ 30 viên",
    unit: "Viên",
    quantity: 300,
    unitPrice: 3000,
    drugGroup: "Thuốc dạ dày",
    tbmt: "Gói thầu thuốc PPI",
    investor: "Bệnh viện Quốc Tế D",
    contractorSelectionMethod: "Chỉ định thầu",
    kqlcntUploadDate: "20/01/2024",
    decisionNumber: "789/QĐ-BVQT",
    decisionDate: "15/01/2024",
    contractorNumber: "NT003",
    location: "Nhà thuốc bệnh viện D",
  },
  {
    id: 4,
    drugName: "Salbutamol 100mcg",
    activeIngredient: "Salbutamol",
    concentration: "100mcg/liều",
    gdklh: "EU-54321-20",
    routeOfAdministration: "Hít",
    dosageForm: "Bình xịt định liều",
    expiryDate: "03/2025",
    manufacturer: "GSK",
    manufacturingCountry: "Anh",
    packaging: "Bình 200 liều",
    unit: "Bình",
    quantity: 200,
    unitPrice: 75000,
    drugGroup: "Thuốc hô hấp",
    tbmt: "Gói thầu thuốc hen",
    investor: "Bệnh viện Phổi E",
    contractorSelectionMethod: "Đấu thầu rộng rãi",
    kqlcntUploadDate: "10/03/2024",
    decisionNumber: "012/QĐ-BVP",
    decisionDate: "05/03/2024",
    contractorNumber: "NT004",
    location: "Kho trung tâm",
  },
  {
    id: 5,
    drugName: "Metformin 850mg",
    activeIngredient: "Metformin Hydrochloride",
    concentration: "850mg",
    gdklh: "VN-98765-23",
    routeOfAdministration: "Uống",
    dosageForm: "Viên nén bao phim",
    expiryDate: "11/2026",
    manufacturer: "Công ty Dược phẩm Imexpharm",
    manufacturingCountry: "Việt Nam",
    packaging: "Hộp 5 vỉ x 20 viên",
    unit: "Viên",
    quantity: 800,
    unitPrice: 800,
    drugGroup: "Thuốc tiểu đường",
    tbmt: "Gói thầu thuốc mãn tính",
    investor: "Trung tâm Kiểm soát bệnh tật F",
    contractorSelectionMethod: "Mua sắm trực tiếp",
    kqlcntUploadDate: "25/02/2024",
    decisionNumber: "321/QĐ-KSBT",
    decisionDate: "20/02/2024",
    contractorNumber: "NT005",
    location: "Phòng khám đa khoa G",
  },
];
